# Load balancer to expose the service
apiVersion: v1
kind: Service
metadata:
  name: silimate-platform-service
spec:
  type: LoadBalancer
  selector:
    app: silimate
  ports:
    - name: http
      port: 8080
      targetPort: 80
    - name: https
      port: 8443
      targetPort: 43
