# Shared volume claim for all pods
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# Volume for all pods
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  hostPath:
    path: /silimate/share
